### ISSUE TITLE
Code provided does not work.

### ISSUE THREAD

**Issue by jacobyoby** [MicrosoftDocs/OfficeDocs-O365ITPro#114] opened 2018-12-06 23:00 UTC
Upgrade-DistributionGroup does not appear to accept a pipeline.

PS C:\Users\jacobd&gt; Get-EligibleDistributionGroupForMigration  | Upgrade-DistributionGroup
The input object cannot be bound to any parameters for the command either because the command does not take pipeline
input or the input and its properties do not match any of the parameters that take pipeline input.
    + CategoryInfo          : InvalidArgument: (Microsoft.Excha...stributionGroup:PSObject) [Upgrade-DistributionGroup
   ], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Upgrade-DistributionGroup
    + PSComputerName        : outlook.office365.com

I had to use this.
PS C:\Users\jacobd&gt; Get-EligibleDistributionGroupForMigration | foreach-object {Upgrade-DistributionGroup -DlIdentities
$_.primarysmtpaddress}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10dbb56e-1c52-8fa0-0d3d-bab6d50519d0
* Version Independent ID: ff6585cd-9d68-ed1c-ee5f-1f451457dbef
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook](https://docs.microsoft.com/en-us/office365/admin/manage/upgrade-distribution-lists?redirectSourcePath=%252fen-US%252farticle%252fMigrate-distribution-lists-to-Office-365-Groups-Admin-help-787d7a75-e201-46f3-a242-f698162ff09f&view=o365-worldwide#what-to-do-if-the-upgrade-doesnt-work)
* Content Source: [Office365-Admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment] 2018-12-14 18:13
@sonika24 Could you investigate this for me please?

**Comment by sonika24** [comment] 2018-12-14 18:16
Sure



On 14-Dec-2018, at 11:43 PM, AndreaBarr <notifications@github.com<mailto:notifications@github.com>> wrote:


@sonika24<https://github.com/sonika24> Could you investigate this for me please?

**Comment by mypil** [comment] 2019-02-14 17:53
@jacobyoby - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-02-14 17:53
@AndreaBarr - This issue can be closed. Thank you.

**Comment by jacobyoby** [comment] 2019-02-14 19:15
Still doesn't accept a pipe.

PS C:\Users\jacobd> Get-EligibleDistributionGroupForMigration | Upgrade-DistributionGroup
The input object cannot be bound to any parameters for the command either because the command does not take pipeline
input or the input and its properties do not match any of the parameters that take pipeline input.
    + CategoryInfo          : InvalidArgument: (Microsoft.Excha...stributionGroup:PSObject) [Upgrade-DistributionGroup
   ], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Upgrade-DistributionGroup
    + PSComputerName        : outlook.office365.com

The input object cannot be bound to any parameters for the command either because the command does not take pipeline
input or the input and its properties do not match any of the parameters that take pipeline input.
    + CategoryInfo          : InvalidArgument: (Microsoft.Excha...stributionGroup:PSObject) [Upgrade-DistributionGroup
   ], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Upgrade-DistributionGroup
    + PSComputerName        : outlook.office365.com

**Comment by mypil** [comment] 2019-02-14 19:44
@j0rt3g4 - please assist with this query. Thank you.

**Comment by j0rt3g4** [comment] 2019-02-14 19:48
@mypil  Will do

**Comment by j0rt3g4** [comment] 2019-02-14 19:52
Hi @jacobyoby  The resolution of this is not based in the "allowance or not" of the items over the pipeline.
The commands have been updated to work with the new code provided.
So ...
Get-EligibleDistributionGroupForMigration | Upgrade-DistributionGroup
Won't work because the "Upgrade-DistributionGroup" cmdlet doesn't take objects on the pipeline 
So using the | between them won't work.

What it works is the way like the code you provided that was integrated on the solution merged by @Sirkkuw  yesterday. The Get-EligibleDistributionGroupForMigration | Upgrade-DistributionGroup is no longer on the documentation because has been corrected.

**Comment by mypil** [comment] 2019-02-14 19:57
@jacobyoby - please check and let us know if @j0rt3g4 has resolved your issue. Thanks.

**Comment by jacobyoby** [comment] 2019-02-14 20:07
I did not see the new commands. 

Thank you and sorry.

**Comment by j0rt3g4** [comment] 2019-02-14 20:08
@jacobyoby  Please Reload the page using CTRL+F5 (probably is that is a cache issue)

**Closed** 2019-02-14 21:51 UTC
