### ISSUE TITLE
檔案中找不到關聯識別碼rld251的圖像部分

### ISSUE THREAD

**Issue by huixin0930** [MicrosoftDocs/OfficeDocs-O365ITPro#89] opened 2018-11-22 15:42 UTC
我是使用office for mac word 15.23(2016) 大量授權版
請問檔案中圖片大量遺失該如何回復？

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: db1be7ae-040e-8939-309f-804d4598ccfa
* Version Independent ID: 976a9ca1-63a4-764b-4cab-da120cb0d8c3
* Content: [台灣的支援資訊](https://docs.microsoft.com/zh-tw/office365/admin/support/taiwan?view=o365-worldwide)
* Content Source: [Office365-Admin/support/taiwan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/taiwan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment] 2018-11-26 20:03
@huixin0930 Thank you for this inquiry

Let me get this missing files issue over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment] 2019-02-11 19:00
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment] 2019-02-11 19:55
@huixin0930.  Can you please provide more details about this issue "檔案中找不到關聯識別碼rld251的圖像部分"   I cannot reproduce the issue on this page: https://docs.microsoft.com/zh-tw/office365/admin/support/taiwan?view=o365-worldwide 
你能提供更多關於這個問題的細節嗎？"檔案中找不到關聯識別碼rld251的圖像部分"
我無法在此頁面上重現問題 https://docs.microsoft.com/zh-tw/office365/admin/support/taiwan?view=o365-worldwide

**Comment by mypil** [comment] 2019-02-18 18:21
@huixin0930 - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!

**Comment by mypil** [comment] 2019-02-18 18:21
@AndreaBarr - This issue can be closed. Thank you.

**Closed** 2019-02-19 18:47 UTC
