### ISSUE TITLE
[LOC] "<電話番号_gt" needs to be replaced with "<電話番号>"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#502] opened 2019-05-21 03:55 UTC
https://docs.microsoft.com/ja-jp/office365/kaizala/aad-sync-with-tul

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ed7dcf14-9ff3-7567-3307-5e9715546462
* Version Independent ID: 60b19aad-4f77-c1e1-ff24-d30669f02153
* Content: [Kaizala ディレクトリと azure Active Directory の同期](https://docs.microsoft.com/ja-jp/office365/kaizala/aad-sync-with-tul)
* Content Source: [Office365-Kaizala/aad-sync-with-tul.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/aad-sync-with-tul.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment] 2019-05-21 09:15
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-05-21 09:24
@officedocsbot assign @OfficeGlobal
@officedocsbot add label localization

**Comment by mypil** [comment] 2019-05-21 09:24
@OfficeGlobal - Can you please assist with this Translation (Localization) issue?

**Comment by OfficeGlobal** [comment] 2019-05-23 06:37
Working on a fix

**Comment by OfficeGlobal** [comment] 2019-05-28 13:32
@hyoshioka0128 , @mypil topic has been HumanTranslated, the issue is fixed including the related issues: #503 | #512

**Comment by mypil** [comment] 2019-05-30 15:14
@hyoshioka0128 - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-05-30 15:15
@officedocsbot close

**Closed by mypil** 2019-05-30 15:15 UTC
Labels: localization
