### ISSUE TITLE
Buy a domain redirects to a Microsoft's partner page

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ITPro#462] opened 2019-05-01 12:58 UTC
Hello. Please add notes to explain under what circumstances the "Buy a domain" selection redirects you to a Microsoft partner's support page instead of allowing you to purchase a domain. In some situations, when selecting to "Buy a domain" the reply from the web portal is "You can buy a domain directly from [Microsoft Partner's Name]". Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8536a8-9f8e-11be-09bd-1b5b55dce588
* Version Independent ID: 985d25d7-b37e-a256-468d-fe23bd6f84cf
* Content: [Buy a domain name in Office 365](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/buy-a-domain-name?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/buy-a-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/buy-a-domain-name.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment] 2019-05-01 14:15
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-05-01 14:53
@adrianwells - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment] 2019-05-01 16:22
@adrianwells  Thank you for submitting the feedback. I'm not able to reproduce the situation. Is  it getting redirected your Microsoft partner's page or does it redirect it to one of the partners who sell domain?

Regards
Sriraman MS

**Comment by adrianwells** [comment] 2019-05-01 16:27
@msbemba A message appears within Microsoft 365 portal with directions to go to a Microsoft partner's URL to purchase a domain. It does not appear in each tenant - maybe where you are testing does not have this experience hence it is not being reproduced?

**Comment by adrianwells** [comment] 2019-05-01 16:30
@msbemba here's a screen capture
<img width="644" alt="2019-05-01 12_29_17-Microsoft 365 admin center - Domains" src="https://user-images.githubusercontent.com/23338636/57028371-e8a44d80-6c0c-11e9-8d4d-e1a5dabd57f2.png">

**Comment by msbemba** [comment] 2019-05-01 17:15
@adrianwells Was this tenant Purchased directly from Microsoft or was it through a partner?

**Comment by adrianwells** [comment] 2019-05-01 18:23
In this case it was a Microsoft partner.

**Comment by msbemba** [comment] 2019-05-01 20:08
@adrianwells That is  the reason why someone would see the redirection to a partners page. When the tenant is setup/purchased from a Microsoft partner, The licenses and Domain are also purchased through partner channel. The document refers to  tenants purchased from Microsoft. I'll add a note to the document about the redirection to the partners page for  tenants  not purchased directly from Microsoft. Hope that helps!

Regards
Sriraman

**Comment by msbemba** [comment] 2019-05-02 16:52
@adrianwells Created a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/465 to add a note about the redirection. Thanks again for  your feedback.

**Comment by mypil** [comment] 2019-05-07 11:59
@adrianwells  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-05-07 11:59
@officedocsbot close

**Closed by mypil** 2019-05-07 11:59 UTC

**Comment by adrianwells** [comment] 2019-05-07 12:51
@mypil Thank you. Made a few formatting improvements in PR #471
