### ISSUE TITLE
Promote to Home Tab

### ISSUE THREAD

**Issue by DFritzke** [MicrosoftDocs/OfficeDocs-O365ITPro#412] opened 2019-04-05 20:38 UTC
Has this option changed?  I do not see this in the App Launcher.

In Service,
Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368890ff-2835-ca55-b1c6-29cbe47c2244
* Version Independent ID: 03bbe66d-e3cb-9fe1-c77c-4741276c43d0
* Content: [Add custom tiles to the app launcher](https://docs.microsoft.com/en-us/office365/admin/manage/customize-the-app-launcher?redirectSourcePath=%252fen-gb%252farticle%252fAdd-custom-tiles-to-the-app-launcher-1136115a-75af-4497-b693-640c4ce70bc6&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment] 2019-04-08 07:16
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-04-08 09:20
@DFritzke - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by DFritzke** [comment] 2019-04-08 12:13
Thanks Joyce

In Service,

Dave Fritzke
Information Technology Executive
YMCA of Metropolitan Milwaukee
414.274.0773 Office
414.534.6402 Cell

Sent from my mobile device.

________________________________

**Comment by msbemba** [comment] 2019-04-11 21:20
@DFritzke Thank you for the feedback. Do you have difficulty in finding the option to add custom tile ? Or are you not able to find the added Custom tile in the app launcher?

**Comment by DFritzke** [comment] 2019-04-11 21:49
I can find it in the application launcher but does not have the option to save to the home screen as the directions state.

In Service,

Dave Fritzke
Information Technology Executive
YMCA of Metropolitan Milwaukee
414.274.0773 Office
414.534.6402 Cell

Sent from my mobile device.

________________________________

**Comment by msbemba** [comment] 2019-04-11 22:32
@dfritzke I'm able to reproduce the problem, I'll check if this is a Bug or if the options have changed.

**Comment by msbemba** [comment] 2019-04-12 21:11
@DFritzke @mypil  I do not see the Pin to home option any more as well. I can confirm this is a  bug and We may have to contact the support team to see if they can resolve it.

**Comment by DFritzke** [comment] 2019-04-14 02:27
Thanks for looking into it.

In Service,

Dave Fritzke
Information Technology Executive
YMCA of Metropolitan Milwaukee
414.274.0773 Office
414.534.6402 Cell

Sent from my mobile device.

________________________________

**Comment by mypil** [comment] 2019-04-15 08:12
@DFritzke - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment] 2019-04-17 10:05
@officedocsbot close

**Comment by msbemba** [comment] 2019-04-17 22:08
@DFritzke We found that this is by design and changed  instructions in document with latest information. A PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/433 has been created to process and track this change. Thank you again for making our documents look better.

Regards
Sriraman

**Comment by mypil** [comment] 2019-04-18 09:12
@officedocsbot reopen

**Comment by mypil** [comment] 2019-04-19 10:09
@officedocsbot add bug

**Comment by mypil** [comment] 2019-04-19 10:10
@officedocsbot add label bug

**Comment by mypil** [comment] 2019-05-07 09:53
@DFritzke  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-05-07 09:53
@officedocsbot close

**Closed by mypil** 2019-05-07 09:53 UTC
Labels: bug
